services:
  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_DATABASE: b2b_support_bot
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  mongo_data:
